### ISSUE TITLE
Overrode my init() function :(

### ISSUE THREAD

**Issue by taigrr** [AdamCollins/JustJS#1]
This framework broke my code! I wrote an init() function, and everything was working. I wanted to use your library, so I included it after my include script, and it called my function too early and then overrode the whole thing so I couldn't even add a checking condition so I could re-run it again later at the proper time!

**Comment by AdamCollins** [comment]
Hi, Taigrr. 
I have updated the library to avoid overriding init methods.
Please re-clone the library and it should be working.

Thank you for raising this issue and our apologies for the delay.
—Adam from the JustJS team

**Comment by taigrr** [comment]
Thank you so much!
